-- Alignement métier des rôles : TENANT→LOCATAIRE, LANDLORD→BAILLEUR, ARTISAN→PRESTATAIRE.

CREATE TYPE "Role_new" AS ENUM ('ADMIN', 'BAILLEUR', 'LOCATAIRE', 'PRESTATAIRE');

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING (
  CASE "role"::text
    WHEN 'TENANT' THEN 'LOCATAIRE'::"Role_new"
    WHEN 'LANDLORD' THEN 'BAILLEUR'::"Role_new"
    WHEN 'ADMIN' THEN 'ADMIN'::"Role_new"
    WHEN 'ARTISAN' THEN 'PRESTATAIRE'::"Role_new"
    ELSE 'LOCATAIRE'::"Role_new"
  END
);

DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'LOCATAIRE'::"Role";
